title: Sam Fleetwood # your name (or website title) here
logo: "/images/LinkedInpfp-modified.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Edit these links below   
  <br>
  in _config.yml 
  <br><br>
  <a href="https://www.linkedin.com/in/sam-fleetwood/">LinkedIn</a> 
  <br>
  <a href="/pdf/Sam Fleetwood - Resume.pdf" class="btn btn--info">Resume</a>  
  <br>
  <a href="https://github.com/samfleet">GitHub</a>  
  <br>
  
theme: jekyll-theme-minimal
