title: Sam Fleetwood # your name (or website title) here
logo: "/images/LinkedInpfp-modified.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Edit these links below   
  <br>
  in _config.yml 
  <br><br>
  <a href="https://www.linkedin.com/in/sam-fleetwood/">LinkedIn</a> 
  <br>
  <a href="/pdf/Sam Fleetwood - Resume.pdf">Resume</a>  
  <br>
  <a href="https://bowen.finance/" class="btn btn--info">Portfolio</a>  
  <br>
  <a href="https://www.GitHub.com/donbowen/">GitHub</a>  
  <br>
  <a href="https://www.GitHub.com/donbowen/">Twitter</a>  
  <br>
  <a href="https://www.GitHub.com/donbowen/">Youtube</a> 
  
theme: jekyll-theme-minimal
